### ISSUE TITLE
奇怪的异常未捕获导致系统崩溃软重启

### ISSUE THREAD

**Issue by KawaiiZapic** [ichenhe/QQ-Notify-Evolution#27]
Android 12, Nevo 6.3, Nevo非Root工作, 未启用内源模式, 启用了消息同步移除
```
--------- beginning of crash
01-31 15:41:46.455  3703  3703 E AndroidRuntime: FATAL EXCEPTION: main
01-31 15:41:46.455  3703  3703 E AndroidRuntime: Process: cc.chenhe.qqnotifyevo, PID: 3703
01-31 15:41:46.455  3703  3703 E AndroidRuntime: java.lang.RuntimeException: Unable to create service cc.chenhe.qqnotifyevo.service.NevoDecorator: java.lang.NullPointerException
01-31 15:41:46.455  3703  3703 E AndroidRuntime: 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4500)
01-31 15:41:46.455  3703  3703 E AndroidRuntime: 	at android.app.ActivityThread.access$1700(ActivityThread.java:247)
01-31 15:41:46.455  3703  3703 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2072)
01-31 15:41:46.455  3703  3703 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
01-31 15:41:46.455  3703  3703 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
01-31 15:41:46.455  3703  3703 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
01-31 15:41:46.455  3703  3703 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7839)
01-31 15:41:46.455  3703  3703 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-31 15:41:46.455  3703  3703 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
01-31 15:41:46.455  3703  3703 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
01-31 15:41:46.455  3703  3703 E AndroidRuntime: Caused by: java.lang.NullPointerException
01-31 15:41:46.455  3703  3703 E AndroidRuntime: 	at cc.chenhe.qqnotifyevo.utils.UtilsKt.getCacheDir(Utils.kt:137)
01-31 15:41:46.455  3703  3703 E AndroidRuntime: 	at cc.chenhe.qqnotifyevo.utils.UtilsKt.getAvatarDiskCacheDir(Utils.kt:154)
01-31 15:41:46.455  3703  3703 E AndroidRuntime: 	at cc.chenhe.qqnotifyevo.core.NotificationProcessor.<init>(NotificationProcessor.kt:173)
01-31 15:41:46.455  3703  3703 E AndroidRuntime: 	at cc.chenhe.qqnotifyevo.core.NevoNotificationProcessor.<init>(NevoNotificationProcessor.kt:18)
01-31 15:41:46.455  3703  3703 E AndroidRuntime: 	at cc.chenhe.qqnotifyevo.service.NevoDecorator.onCreate(NevoDecorator.kt:65)
01-31 15:41:46.455  3703  3703 E AndroidRuntime: 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4487)
01-31 15:41:46.455  3703  3703 E AndroidRuntime: 	... 9 more
01-31 15:41:47.736  3815  3815 E AndroidRuntime: FATAL EXCEPTION: main
01-31 15:41:47.736  3815  3815 E AndroidRuntime: Process: cc.chenhe.qqnotifyevo, PID: 3815
01-31 15:41:47.736  3815  3815 E AndroidRuntime: java.lang.RuntimeException: Unable to create service cc.chenhe.qqnotifyevo.service.NevoDecorator: java.lang.NullPointerException
01-31 15:41:47.736  3815  3815 E AndroidRuntime: 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4500)
01-31 15:41:47.736  3815  3815 E AndroidRuntime: 	at android.app.ActivityThread.access$1700(ActivityThread.java:247)
01-31 15:41:47.736  3815  3815 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2072)
01-31 15:41:47.736  3815  3815 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
01-31 15:41:47.736  3815  3815 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
01-31 15:41:47.736  3815  3815 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
01-31 15:41:47.736  3815  3815 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7839)
01-31 15:41:47.736  3815  3815 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-31 15:41:47.736  3815  3815 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
01-31 15:41:47.736  3815  3815 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
01-31 15:41:47.736  3815  3815 E AndroidRuntime: Caused by: java.lang.NullPointerException
01-31 15:41:47.736  3815  3815 E AndroidRuntime: 	at cc.chenhe.qqnotifyevo.utils.UtilsKt.getCacheDir(Utils.kt:137)
01-31 15:41:47.736  3815  3815 E AndroidRuntime: 	at cc.chenhe.qqnotifyevo.utils.UtilsKt.getAvatarDiskCacheDir(Utils.kt:154)
01-31 15:41:47.736  3815  3815 E AndroidRuntime: 	at cc.chenhe.qqnotifyevo.core.NotificationProcessor.<init>(NotificationProcessor.kt:173)
01-31 15:41:47.736  3815  3815 E AndroidRuntime: 	at cc.chenhe.qqnotifyevo.core.NevoNotificationProcessor.<init>(NevoNotificationProcessor.kt:18)
01-31 15:41:47.736  3815  3815 E AndroidRuntime: 	at cc.chenhe.qqnotifyevo.service.NevoDecorator.onCreate(NevoDecorator.kt:65)
01-31 15:41:47.736  3815  3815 E AndroidRuntime: 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4487)
01-31 15:41:47.736  3815  3815 E AndroidRuntime: 	... 9 more
```

**Comment by ichenhe** [comment]
感谢反馈。

已修复，请更新到  [v2.2.6 +](https://github.com/ichenhe/QQ-Notify-Evolution/releases)

**Comment by KawaiiZapic** [comment]
> 感谢反馈。
> 
> 已修复，请更新到 [v2.2.6 +](https://github.com/ichenhe/QQ-Notify-Evolution/releases)

顺带问一下, Nevo模式无法更新原有通知是Nevo的限制还是还没实现

**Comment by ichenhe** [comment]
> Nevo模式无法更新原有通知是Nevo的限制还是还没实现

可以更新啊

**Comment by ichenhe** [comment]
emmm 发现个尴尬的事情。

似乎崩溃的原因不是这个。你试试看，如果还有问题就 reopen 这个 issue

**Comment by KawaiiZapic** [comment]
跟女娲石的作者反馈后, 发现是aosp的bug, 目前看起来没什么好办法.
